# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0baf5ae0414c08381e76db4689173bfa5e0039192d9132a1f2f19b566d75c8bbfc27cec9f899ba08a9daa2b85e99951d18c0373a83ae87e3ddaf8c3c7f98f381

test:
  secret_key_base: 5768f19c916187b3863c4dd11c83d80375893c3fb92609c8b24140a8b08c817f3e3504c4b31c353289cb15599d438448d51611065ff1370759e69a4725dfe168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
